k8sImageAvailabilityExporter:
  image:
    repository: registry.deckhouse.io/k8s-image-availability-exporter/k8s-image-availability-exporter
    tag: v0.2.1
    pullPolicy: IfNotPresent
  replicas: 1
  resources: {}

serviceMonitor:
  enabled: false
  interval: 15s

prometheusRule:
  enabled: false
  defaultGroupsEnabled: true
  additionalGroups: []
