{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "k8s-image-availability-exporter.fullname" . }}
spec:
  groups:
{{- if .Values.prometheusRule.defaultGroupsEnabled }}
  - name: k8s-image-availability-exporter.rules
    rules:
    - alert: DeploymentImageUnavailable
      expr: |
        max by (namespace, deployment, container, image) (
          k8s_image_availability_exporter_deployment_available == 0
        )
      annotations:
        message: >
          Image {{`{{ $labels.image }}`}} from container {{`{{ $labels.container }}`}}
          in deployment {{`{{ $labels.deployment }}`}}
          from namespace {{`{{ $labels.namespace }}`}}
          is not available in docker registry.
      labels:
        severity: critical
    - alert: StatefulSetImageUnavailable
      expr: |
        max by (namespace, statefulset, container, image) (
          k8s_image_availability_exporter_statefulset_available == 0
        )
      annotations:
        message: >
          Image {{`{{ $labels.image }}`}} from container {{`{{ $labels.container }}`}}
          in statefulSet {{`{{ $labels.statefulset }}`}}
          from namespace {{`{{ $labels.namespace }}`}}
          is not available in docker registry.
      labels:
        severity: critical
    - alert: DaemonSetImageUnavailable
      expr: |
        max by (namespace, daemonset, container, image) (
          k8s_image_availability_exporter_daemonset_available == 0
        )
      annotations:
        message: >
          Image {{`{{ $labels.image }}`}} from container {{`{{ $labels.container }}`}}
          in daemonSet {{`{{ $labels.daemonset }}`}}
          from namespace {{`{{ $labels.namespace }}`}}
          is not available in docker registry.
      labels:
        severity: critical
    - alert: CronJobImageUnavailable
      expr: |
        max by (namespace, cronjob, container, image) (
          k8s_image_availability_exporter_cronjob_available == 0
        )
      annotations:
        message: >
          Image {{`{{ $labels.image }}`}} from container {{`{{ $labels.container }}`}}
          in cronJob {{`{{ $labels.cronjob }}`}}
          from namespace {{`{{ $labels.namespace }}`}}
          is not available in docker registry.
      labels:
        severity: critical
{{- end }}

{{- if .Values.prometheusRule.additionalGroups }}
{{ .Values.prometheusRule.additionalGroups | toYaml | indent 2}}
{{- end }}

{{- end }}
