k8sImageAvailabilityExporter:
  image:
    repository: registry.deckhouse.io/k8s-image-availability-exporter/k8s-image-availability-exporter
    tag: v0.3.0
    pullPolicy: IfNotPresent
  replicas: 1
  resources: {}
  args:
    - --bind-address=:8080
  
serviceMonitor:
  enabled: false
  interval: 15s
  additional_labels: 
    enabled: false
    prometheus_service_monitor_selector: 
      release: "serviceMonitorSelector_for_Prometheus"

prometheusRule:
  enabled: false
  defaultGroupsEnabled: true
  additionalGroups: []
